// Seeds the database with three realistic sample meetings (real Windows-SAPI
// synthesized audio + exactly-timed transcripts, see scripts/synthesize-seed-audio.ps1
// and public/seed-media/*.timing.json) so the app never opens to an empty state.
//
// Summaries and action items below are hand-authored to match the seeded
// dialogue rather than generated by a live LLM call at seed time (that would
// make `npm run seed` hard-depend on an ANTHROPIC_API_KEY being configured
// before the app can even be demoed). The real Anthropic-backed generator in
// src/lib/ai.ts is what a real uploaded recording goes through at runtime —
// same output shape, real model call.

import "dotenv/config";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { PrismaClient, HighlightLabel, SummaryTemplate } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { SEED_OWNER_ID } from "../src/lib/seed-claim";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const mediaDir = join(__dirname, "..", "public", "seed-media");

type TimingLine = { index: number; speaker: string; text: string; startMs: number; endMs: number };
type TimingFile = {
  slug: string;
  title: string;
  occurredAt: string;
  participants: { name: string; email: string; voice: string; isHost: boolean }[];
  totalMs: number;
  mediaFile: string;
  lines: TimingLine[];
};

function loadTiming(slug: string): TimingFile {
  const raw = readFileSync(join(mediaDir, `${slug}.timing.json`), "utf8").replace(/^﻿/, "");
  return JSON.parse(raw);
}

function findLineStart(timing: TimingFile, matcher: (text: string) => boolean): number {
  const line = timing.lines.find((l) => matcher(l.text.toLowerCase()));
  if (!line) throw new Error(`No matching line found for highlight in ${timing.slug}`);
  return line.startMs;
}

async function seedMeeting(opts: {
  timing: TimingFile;
  summaries: { template: SummaryTemplate; content: string }[];
  actionItems: { text: string; owner?: string; dueDate?: Date }[];
  highlights: { matcher: (t: string) => boolean; label: HighlightLabel; note: string }[];
}) {
  const { timing, summaries, actionItems, highlights } = opts;

  const meeting = await prisma.meeting.create({
    data: {
      ownerId: SEED_OWNER_ID,
      title: timing.title,
      occurredAt: new Date(timing.occurredAt),
      durationSec: Math.round(timing.totalMs / 1000),
      mediaUrl: `/seed-media/${timing.mediaFile}`,
      mediaType: "AUDIO",
      source: "SEED",
    },
  });

  const participantByName = new Map<string, string>();
  for (const p of timing.participants) {
    const participant = await prisma.participant.create({
      data: {
        meetingId: meeting.id,
        name: p.name,
        email: p.email,
        isHost: p.isHost,
      },
    });
    participantByName.set(p.name, participant.id);
  }

  await prisma.transcriptLine.createMany({
    data: timing.lines.map((l) => ({
      meetingId: meeting.id,
      participantId: participantByName.get(l.speaker) ?? null,
      speakerName: l.speaker,
      startMs: l.startMs,
      endMs: l.endMs,
      text: l.text,
      order: l.index,
    })),
  });

  for (const s of summaries) {
    await prisma.summary.create({
      data: { meetingId: meeting.id, template: s.template, content: s.content },
    });
  }

  for (const a of actionItems) {
    await prisma.actionItem.create({
      data: { meetingId: meeting.id, text: a.text, owner: a.owner, dueDate: a.dueDate },
    });
  }

  for (const h of highlights) {
    await prisma.highlight.create({
      data: {
        meetingId: meeting.id,
        timestampMs: findLineStart(timing, h.matcher),
        label: h.label,
        note: h.note,
      },
    });
  }

  console.log(`Seeded meeting "${timing.title}" (${meeting.id})`);
}

async function main() {
  await prisma.user.upsert({
    where: { id: SEED_OWNER_ID },
    update: {},
    create: {
      id: SEED_OWNER_ID,
      name: "Seed Data",
      email: null,
    },
  });

  // Clear previous seed run so `npm run seed` is idempotent.
  await prisma.meeting.deleteMany({ where: { ownerId: SEED_OWNER_ID } });

  const productSync = loadTiming("product-sync");
  await seedMeeting({
    timing: productSync,
    summaries: [
      {
        template: "GENERAL",
        content: `## Product Sync — Q3 Roadmap

**Search revamp** is ~70% done — full-text indexing is live in staging, ranking logic still needs to be wired up. Tight but achievable for the Sep 15 launch if an extra engineer helps this week.

**Mobile notifications** are blocked on design finalizing the notification preferences screen. Alex will chase design for an answer by Thursday.

**Onboarding feedback** has been strongly positive — several customers called out the new flow as a highlight. Team will keep an eye on the metrics over the next couple of weeks to confirm the trend holds.

Priya will send the updated roadmap doc after the call.`,
      },
    ],
    actionItems: [
      { text: "Pull Sam onto search ranking work for the rest of the week", owner: "Alex Rivera" },
      { text: "Send Sam the ranking spec", owner: "Priya Nair" },
      { text: "Follow up with design on the notification preferences screen", owner: "Alex Rivera", dueDate: new Date("2026-09-10T17:00:00.000Z") },
      { text: "Send the updated Q3 roadmap doc", owner: "Priya Nair" },
    ],
    highlights: [
      { matcher: (t) => t.includes("pull sam off the billing project"), label: "POSITIVE_REACTION", note: "Alex commits to unblocking search ranking by reassigning Sam." },
      { matcher: (t) => t.includes("that one's blocked"), label: "NEEDS_REVIEW", note: "Mobile notifications blocked on design." },
      { matcher: (t) => t.includes("really positive"), label: "POSITIVE_REACTION", note: "Strong customer feedback on new onboarding flow." },
    ],
  });

  const salesDiscovery = loadTiming("sales-discovery");
  await seedMeeting({
    timing: salesDiscovery,
    summaries: [
      {
        template: "GENERAL",
        content: `## Discovery Call — Acme Logistics

Acme's dispatch team manually tracks ~400 shipments/week (growing ~15% QoQ) across three spreadsheets — error-prone and not scaling. Ops director Maria and their IT lead will also need to weigh in.

Acme runs NetSuite for ERP; we have a native connector, which removes a key integration concern. They want to go live before November peak season, with a decision expected in 3–4 weeks. Biggest risk of inaction: missed shipments during peak season, hitting customer trust and renewals.

Next steps: a technical scoping doc for the NetSuite integration, and a proposal reflecting the November timeline, looping in Maria directly.`,
      },
      {
        template: "SALES",
        content: `## Sales Discovery — BANT Summary

**Budget:** Not yet discussed explicitly — to be addressed in the proposal stage.

**Authority:** Sam Whitfield is evaluating; Maria (Ops Director) must sign off, IT lead reviews integration requirements. Recommend looping Maria in early (requested by Sam).

**Need:** Manual, spreadsheet-based shipment tracking (~400/week, +15% QoQ) is error-prone and won't scale. Existing NetSuite ERP integration is a solved problem via our native connector.

**Timeline:** Hard deadline pressure — must be live before November peak season. Decision expected within 3–4 weeks. Highest-leverage angle: cost of inaction is missed shipments during their busiest, highest-visibility stretch.

**Recommended next step:** Fast-track scoping doc + proposal this week to match their compressed evaluation window.`,
      },
    ],
    actionItems: [
      { text: "Send technical scoping doc for the NetSuite integration", owner: "Chris Doyle", dueDate: new Date("2026-09-09T17:00:00.000Z") },
      { text: "Send proposal reflecting the November go-live timeline, cc Maria", owner: "Jordan Blake" },
    ],
    highlights: [
      { matcher: (t) => t.includes("spending way too much time"), label: "FEEDBACK", note: "Core pain point: manual spreadsheet-based shipment tracking." },
      { matcher: (t) => t.includes("native netsuite connector"), label: "POSITIVE_REACTION", note: "Integration concern resolved on the spot." },
      { matcher: (t) => t.includes("missed shipments during our busiest"), label: "NEEDS_REVIEW", note: "Cost-of-inaction / urgency driver for the deal." },
    ],
  });

  const standup = loadTiming("daily-standup");
  await seedMeeting({
    timing: standup,
    summaries: [
      {
        template: "GENERAL",
        content: `## Daily Standup

Search ranking logic is done (ahead of schedule); Sam moved fully onto ranking after wrapping billing early, no blockers. Ranking spec review planned for 3pm today.

Notifications work remains blocked on design finalizing the notification preferences screen — Alex is still waiting to hear back. Sam will hold off starting the notifications backend until that unblocks.`,
      },
    ],
    actionItems: [
      { text: "Review the ranking spec once pushed", owner: "Alex Rivera", dueDate: new Date("2026-09-11T20:00:00.000Z") },
      { text: "Hold off starting the notifications backend until design unblocks", owner: "Sam Okafor" },
    ],
    highlights: [
      { matcher: (t) => t.includes("still blocked"), label: "NEEDS_REVIEW", note: "Notifications still blocked on design." },
    ],
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
