// Seeds the database with three realistic sample meetings (real Windows-SAPI
// synthesized audio + exactly-timed transcripts, see scripts/synthesize-seed-audio.ps1
// and public/seed-media/*.timing.json) so the app never opens to an empty state.
//
// Summaries and action items below are hand-authored to match the seeded
// dialogue rather than generated by a live LLM call at seed time (that would
// make `npm run seed` hard-depend on a GROQ_API_KEY being configured before
// the app can even be demoed). The real Groq-backed generator in
// src/lib/ai.ts is what a real uploaded recording goes through at runtime —
// same output shape, real model call.
//
// These are templates: they live under the sample-owner account and are
// copied into every new account (src/lib/samples.ts).

import "dotenv/config";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { PrismaClient, HighlightLabel, SummaryTemplate } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { SAMPLE_OWNER_ID as SEED_OWNER_ID } from "../src/lib/sample-owner";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const mediaDir = join(__dirname, "..", "public", "seed-media");

type TimingLine = { index: number; speaker: string; text: string; startMs: number; endMs: number };
type TimingFile = {
  slug: string;
  title: string;
  occurredAt: string;
  participants: { name: string; email: string; voice: string; isHost: boolean }[];
  totalMs: number;
  mediaFile: string;
  lines: TimingLine[];
};

function loadTiming(slug: string): TimingFile {
  const raw = readFileSync(join(mediaDir, `${slug}.timing.json`), "utf8").replace(/^﻿/, "");
  return JSON.parse(raw);
}

function findLineStart(timing: TimingFile, matcher: (text: string) => boolean): number {
  const line = timing.lines.find((l) => matcher(l.text.toLowerCase()));
  if (!line) throw new Error(`No matching transcript line in ${timing.slug}`);
  return line.startMs;
}

// Summaries cite their sources as [[a phrase from the line]]; stored as the
// [t=ms] citations the app renders as jump-to-moment chips.
function resolveSeedCitations(timing: TimingFile, content: string) {
  return content.replace(/\[\[([^\]]+)\]\]/g, (_m, phrase: string) => {
    const needle = phrase.toLowerCase();
    return `[t=${findLineStart(timing, (t) => t.includes(needle))}]`;
  });
}

async function seedMeeting(opts: {
  timing: TimingFile;
  // Topics for the timeline; `at` finds the line each one starts on.
  chapters: { title: string; at: (t: string) => boolean }[];
  summaries: { template: SummaryTemplate; content: string }[];
  // `at` finds the line where the commitment was made; its start time pins
  // the item on the meeting timeline.
  actionItems: { text: string; owner?: string; dueDate?: Date; at: (t: string) => boolean }[];
  highlights: { matcher: (t: string) => boolean; label: HighlightLabel; note: string }[];
}) {
  const { timing, chapters, summaries, actionItems, highlights } = opts;

  const meeting = await prisma.meeting.create({
    data: {
      ownerId: SEED_OWNER_ID,
      title: timing.title,
      occurredAt: new Date(timing.occurredAt),
      durationSec: Math.round(timing.totalMs / 1000),
      mediaUrl: `/seed-media/${timing.mediaFile}`,
      mediaType: "AUDIO",
      source: "SEED",
    },
  });

  const participantByName = new Map<string, string>();
  for (const p of timing.participants) {
    const participant = await prisma.participant.create({
      data: {
        meetingId: meeting.id,
        name: p.name,
        email: p.email,
        isHost: p.isHost,
      },
    });
    participantByName.set(p.name, participant.id);
  }

  await prisma.transcriptLine.createMany({
    data: timing.lines.map((l) => ({
      meetingId: meeting.id,
      participantId: participantByName.get(l.speaker) ?? null,
      speakerName: l.speaker,
      startMs: l.startMs,
      endMs: l.endMs,
      text: l.text,
      order: l.index,
    })),
  });

  const starts = chapters.map((c, i) => (i === 0 ? 0 : findLineStart(timing, c.at)));
  await prisma.chapter.createMany({
    data: chapters.map((c, i) => ({
      meetingId: meeting.id,
      title: c.title,
      startMs: starts[i],
      endMs: i + 1 < chapters.length ? starts[i + 1] : timing.totalMs,
      order: i,
    })),
  });

  for (const s of summaries) {
    await prisma.summary.create({
      data: { meetingId: meeting.id, template: s.template, content: resolveSeedCitations(timing, s.content) },
    });
  }

  for (const a of actionItems) {
    await prisma.actionItem.create({
      data: {
        meetingId: meeting.id,
        text: a.text,
        owner: a.owner,
        dueDate: a.dueDate,
        sourceMs: findLineStart(timing, a.at),
      },
    });
  }

  for (const h of highlights) {
    await prisma.highlight.create({
      data: {
        meetingId: meeting.id,
        timestampMs: findLineStart(timing, h.matcher),
        label: h.label,
        note: h.note,
      },
    });
  }

  console.log(`Seeded meeting "${timing.title}" (${meeting.id})`);
}

async function main() {
  await prisma.user.upsert({
    where: { id: SEED_OWNER_ID },
    update: {},
    create: {
      id: SEED_OWNER_ID,
      name: "Seed Data",
      email: null,
    },
  });

  // Clear previous seed run so `npm run seed` is idempotent.
  await prisma.meeting.deleteMany({ where: { ownerId: SEED_OWNER_ID } });

  const productSync = loadTiming("product-sync");
  await seedMeeting({
    timing: productSync,
    chapters: [
      { title: "Search revamp", at: () => true },
      { title: "Notifications blocked", at: (t) => t.includes("what about the mobile notifications") },
      { title: "Onboarding feedback", at: (t) => t.includes("one more thing, i want to flag") },
      { title: "Recap", at: (t) => t.includes("to summarize") },
    ],
    summaries: [
      {
        template: "GENERAL",
        content: `**Search revamp** is ~70% done — full-text indexing is live in staging, ranking logic still needs to be wired up. [[seventy percent done]] Tight but achievable for the Sep 15 launch if an extra engineer helps this week. [[one more engineer on ranking]]

**Mobile notifications** are blocked on design finalizing the notification preferences screen. [[that one's blocked]] Alex will chase design for an answer by Thursday. [[follow up with design today]]

**Onboarding feedback** has been strongly positive — several customers called out the new flow as a highlight. [[called it out as a highlight]] Team will keep an eye on the metrics over the next couple of weeks to confirm the trend holds. [[keep an eye on the metrics]]

Priya will send the updated roadmap doc after the call. [[updated roadmap doc]]`,
      },
    ],
    actionItems: [
      { text: "Pull Sam onto search ranking work for the rest of the week", owner: "Alex Rivera", at: (t) => t.includes("pull sam off the billing project") },
      { text: "Send Sam the ranking spec", owner: "Priya Nair", at: (t) => t.includes("send sam the ranking spec") },
      { text: "Follow up with design on the notification preferences screen", owner: "Alex Rivera", dueDate: new Date("2026-09-10T17:00:00.000Z"), at: (t) => t.includes("follow up with design today") },
      { text: "Send the updated Q3 roadmap doc", owner: "Priya Nair", at: (t) => t.includes("updated roadmap doc") },
    ],
    highlights: [
      { matcher: (t) => t.includes("pull sam off the billing project"), label: "POSITIVE_REACTION", note: "Alex commits to unblocking search ranking by reassigning Sam." },
      { matcher: (t) => t.includes("that one's blocked"), label: "NEEDS_REVIEW", note: "Mobile notifications blocked on design." },
      { matcher: (t) => t.includes("really positive"), label: "POSITIVE_REACTION", note: "Strong customer feedback on new onboarding flow." },
    ],
  });

  const salesDiscovery = loadTiming("sales-discovery");
  await seedMeeting({
    timing: salesDiscovery,
    chapters: [
      { title: "Introductions", at: () => true },
      { title: "Why they're looking", at: (t) => t.includes("what's driving you to look") },
      { title: "Decision makers and ERP", at: (t) => t.includes("who else is involved") },
      { title: "Timeline and risk", at: (t) => t.includes("is there a specific date") },
      { title: "Next steps", at: (t) => t.includes("here's what i'd suggest as next steps") },
    ],
    summaries: [
      {
        template: "GENERAL",
        content: `Acme's dispatch team manually tracks ~400 shipments/week (growing ~15% QoQ) across three spreadsheets — error-prone and not scaling. [[spending way too much time]][[somewhere around four hundred]] Ops director Maria and their IT lead will also need to weigh in. [[our ops director, maria]]

Acme runs NetSuite for ERP; we have a native connector, which removes a key integration concern. [[native netsuite connector]] They want to go live before November peak season, with a decision expected in 3–4 weeks. [[peak season starts in november]] Biggest risk of inaction: missed shipments during peak season, hitting customer trust and renewals. [[missed shipments during our busiest]]

Next steps: a technical scoping doc for the NetSuite integration, and a proposal reflecting the November timeline, looping in Maria directly. [[here's what i'd suggest as next steps]]`,
      },
      {
        template: "SALES",
        content: `**Budget:** Not yet discussed explicitly — to be addressed in the proposal stage.

**Authority:** Sam Whitfield is evaluating; Maria (Ops Director) must sign off, IT lead reviews integration requirements. [[our ops director, maria]] Recommend looping Maria in early (requested by Sam). [[loop in maria on the proposal]]

**Need:** Manual, spreadsheet-based shipment tracking (~400/week, +15% QoQ) is error-prone and won't scale. [[spending way too much time]] Existing NetSuite ERP integration is a solved problem via our native connector. [[native netsuite connector]]

**Timeline:** Hard deadline pressure — must be live before November peak season. [[peak season starts in november]] Decision expected within 3–4 weeks. [[three to four weeks]] Highest-leverage angle: cost of inaction is missed shipments during their busiest, highest-visibility stretch. [[missed shipments during our busiest]]

**Recommended next step:** Fast-track scoping doc + proposal this week to match their compressed evaluation window.`,
      },
    ],
    actionItems: [
      { text: "Send technical scoping doc for the NetSuite integration", owner: "Chris Doyle", dueDate: new Date("2026-09-09T17:00:00.000Z"), at: (t) => t.includes("scoping doc over by wednesday") },
      { text: "Send proposal reflecting the November go-live timeline, cc Maria", owner: "Jordan Blake", at: (t) => t.includes("include her directly") },
    ],
    highlights: [
      { matcher: (t) => t.includes("spending way too much time"), label: "FEEDBACK", note: "Core pain point: manual spreadsheet-based shipment tracking." },
      { matcher: (t) => t.includes("native netsuite connector"), label: "POSITIVE_REACTION", note: "Integration concern resolved on the spot." },
      { matcher: (t) => t.includes("missed shipments during our busiest"), label: "NEEDS_REVIEW", note: "Cost-of-inaction / urgency driver for the deal." },
    ],
  });

  // The long, many-speaker case: eight people, one overloaded engineer, and a
  // trade-off that has to be made explicit. Continues threads from the
  // other samples (ranking launch, notifications blocked on design, the Acme
  // deal's NetSuite deadline).
  const q4Planning = loadTiming("q4-planning");
  await seedMeeting({
    timing: q4Planning,
    chapters: [
      { title: "Agenda and goals", at: () => true },
      { title: "Ranking shipped", at: (t) => t.includes("priya, do you want to start") },
      { title: "Notifications unblocked", at: (t) => t.includes("maria, notifications") },
      { title: "Mobile crash reports", at: (t) => t.includes("you flagged support load") },
      { title: "The Acme deal", at: (t) => t.includes("jordan, chris, the acme deal") },
      { title: "Capacity trade-off", at: (t) => t.includes("so this is the real conversation") },
      { title: "Agreeing the plan", at: (t) => t.includes("let me say it back") },
      { title: "Risks and wrap-up", at: (t) => t.includes("can i add one risk") },
    ],
    summaries: [
      {
        template: "GENERAL",
        content: `The team agreed three Q4 priorities, in order, and made the main trade-off explicit: if the NetSuite work overruns, notifications slips, not Acme. [[notifications moves, not acme]]

## Decisions
- **NetSuite hardening for Acme** comes first: a load test with Acme-sized data, plus retry handling for NetSuite rate limits. Sam and Chris, done by 15 October. [[priority one, netsuite hardening]]
- **Mobile notifications** is second. Maria's preference designs are final; Sam writes the API contract first, Omar builds the mobile screen against a mock, and Sam finishes the backend after NetSuite. [[final final. i'll send the files]][[omar builds against a mock]]
- **Recently viewed boosting** in search is third, run by Priya in parallel (about three weeks). [[recently viewed boosting doesn't touch]]
- Full personalization moves to Q1, with a scoping proposal from Priya by the end of October. [[full personalization moves to q1]][[end of october works]]

## Context
- Search ranking shipped on 15 September; first-result click-through is up about 11% week over week. [[click through on the first result]]
- Acme Logistics (around 400 shipments a week, growing 15% a quarter) wants to go live before its November peak. [[four hundred shipments a week]] The NetSuite integration is the one real risk to the deal. [[the one thing that could sink it]] Their ops director singled out how easy the demo was, and their IT lead wants to see the load test results. [[first demo that didn't make her feel]][[see the load test results]]
- Mobile crash reports doubled after the last release because of a bug on older Android phones; the fix ships Thursday. [[crash reports doubled]][[it goes out thursday]]

## Risks
- Sam is needed on two of the three priorities. [[so sam is the bottleneck]]
- If the load test turns up something big, notifications moves. The team agreed this now so it isn't argued about in October. [[if netsuite needs more than two weeks]]`,
      },
    ],
    actionItems: [
      { text: "Send the final notification preference designs, with empty and error states", owner: "Maria Lopez", dueDate: new Date("2026-09-18T17:00:00.000Z"), at: (t) => t.includes("send the files over by friday") },
      { text: "Give a real estimate for the notifications backend once the designs are in", owner: "Sam Okafor", dueDate: new Date("2026-09-16T17:00:00.000Z"), at: (t) => t.includes("yes, wednesday works") },
      { text: "Start the mobile notification preferences screen", owner: "Omar Haddad", dueDate: new Date("2026-09-21T09:00:00.000Z"), at: (t) => t.includes("start on the mobile screen monday") },
      { text: "Add older Android devices to the test lab and put the cost in the planning doc", owner: "Omar Haddad", at: (t) => t.includes("older devices to the test lab") },
      { text: "Write the notifications API contract before switching to NetSuite", owner: "Sam Okafor", at: (t) => t.includes("write the api contract in the first two days") },
      { text: "Load test the NetSuite connector with Acme-sized data and harden retries", owner: "Chris Doyle", dueDate: new Date("2026-10-15T17:00:00.000Z"), at: (t) => t.includes("priority one, netsuite hardening") },
      { text: "Write the personalization proposal for Q1", owner: "Priya Nair", dueDate: new Date("2026-10-30T17:00:00.000Z"), at: (t) => t.includes("end of october works") },
      { text: "Confirm Acme's go-live date and set up a load test review with their IT lead", owner: "Jordan Blake", at: (t) => t.includes("set up a review with their it lead") },
      { text: "Share the Q4 plan: priorities, owners and the agreed trade-off", owner: "Lena Fischer", dueDate: new Date("2026-09-21T09:00:00.000Z"), at: (t) => t.includes("share it by monday") },
      { text: "Schedule a check-in on Sam's sequencing in two weeks", owner: "Lena Fischer", at: (t) => t.includes("put it on the calendar") },
    ],
    highlights: [
      { matcher: (t) => t.includes("the preferences screen is finished"), label: "POSITIVE_REACTION", note: "Notifications unblocked: designs final, tested with six customers." },
      { matcher: (t) => t.includes("first demo that didn't make her feel"), label: "FEEDBACK", note: "Acme's ops director on the demo: ease of use is the differentiator." },
      { matcher: (t) => t.includes("so sam is the bottleneck"), label: "NEEDS_REVIEW", note: "Capacity: Sam is needed on two of the three priorities." },
      { matcher: (t) => t.includes("priority one, netsuite hardening"), label: "HIGHLIGHT", note: "The decision: three priorities, in order, with owners." },
      { matcher: (t) => t.includes("if netsuite needs more than two weeks"), label: "NEEDS_REVIEW", note: "Agreed trade-off: notifications slips before Acme does." },
    ],
  });

  const standup = loadTiming("daily-standup");
  await seedMeeting({
    timing: standup,
    chapters: [
      { title: "Ranking progress", at: () => true },
      { title: "Blocked on design", at: (t) => t.includes("block time for that at three") },
    ],
    summaries: [
      {
        template: "GENERAL",
        content: `Search ranking logic is done (ahead of schedule); Sam moved fully onto ranking after wrapping billing early, no blockers. [[finished the ranking logic]][[wrapped up the billing project early]] Ranking spec review planned for 3pm today. [[block time for that at three]]

Notifications work remains blocked on design finalizing the notification preferences screen — Alex is still waiting to hear back. [[still waiting to hear back]] Sam will hold off starting the notifications backend until that unblocks. [[hold off starting the notifications backend]]`,
      },
    ],
    actionItems: [
      { text: "Review the ranking spec once pushed", owner: "Alex Rivera", dueDate: new Date("2026-09-11T20:00:00.000Z"), at: (t) => t.includes("block time for that at three") },
      { text: "Hold off starting the notifications backend until design unblocks", owner: "Sam Okafor", at: (t) => t.includes("hold off starting the notifications backend") },
    ],
    highlights: [
      { matcher: (t) => t.includes("still blocked"), label: "NEEDS_REVIEW", note: "Notifications still blocked on design." },
    ],
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
